#!/bin/bash

# create a bunch of PNGs (one for each station, named by id)

WHERE=~/Desktop/tmp

for i in `cat id` ; do

  rrdtool graph $WHERE/s$i.png --start now-30m --end now -l -2 -u 58 -r DEF:b=s$i.rrd:bikes:AVERAGE \
               DEF:d=s$i.rrd:docks:AVERAGE LINE2:b#88aadd:"available bikes" LINE2:d#444444:"available docks"

done



